name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Allow Unfree
        run: export NIXPKGS_ALLOW_UNFREE=1

      - name: Run tests 
        run: nix develop --impure -c mvn test

      - name: Run functional tests 
        run: nix develop --impure -c ./run_functional_tests.sh
