name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Run nix develop
        run: nix develop

      - name: Run ls
        working-directory: ./idris-maven-plugin
        run: ls
        
      - name: Run tests
        working-directory: ./idris-maven-plugin
        run: mvn test
